apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-practice
spec:
  replicas: {{ required "replicaCount 까묵지 말라고 했지!" .Values.replicaCount }}
  selector:
    matchLabels:
      app: cicd-practice
  template:
    metadata:
      labels:
        app: cicd-practice
    spec:
      containers:
      - name: cicd-practice
        image: {{ required "image 까묵지 말라고 했지!" .Values.image }}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-practice
spec:
  selector:
    app: cicd-practice
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-practice
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ required "host까묵지 말라고 했지!!!" .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cicd-practice
            port:
              number: 3000