apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-practice
  template:
    metadata:
      labels:
        app: cicd-practice
    spec:
      containers:
      - name: cicd-practice
        image: "709745608741.dkr.ecr.ap-northeast-2.amazonaws.com/pickme_back:0dd66825155dc495fa4326f53f35969073cbc84d"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-practice
spec:
  selector:
    app: cicd-practice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-practice
spec:
  ingressClassName: "nginx"
  rules:
  - host: backend.pickme-ssg.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cicd-practice
            port:
              number: 80
