apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-practice
  template:
    metadata:
      labels:
        app: cicd-practice
    spec:
      containers:
      - name: cicd-practice
        image: public.ecr.aws/e3s0f1s6/pickme_back:966b03a8e177bb4c0dbe02cceafa97277c2034da
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-practice
spec:
  selector:
    app: cicd-practice
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-practice
spec:
  ingressClassName: "nginx"
  rules:
  - host: backend.pickme-ssg.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cicd-practice
            port:
              number: 8086
